version: '3'
services:
  nuxt:
    build:
      context: .
      args:
        SSH_PRIVATE_KEY: ssh_private_key
    command: bash -c "yarn run dev"
    volumes:
      - '.:/nuxtapp'
    ports:
      - '3000:3000'
